version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-a12345678X}
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-12345678}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-password}

volumes:
  mongo_data:
  minio_data:
